variables:
  GITLAB_ENV: test
  SERVICE: ${SERVICE}
  INSTANCE: download-$CI_COMMIT_REF_SLUG
  VERSION: $CI_COMMIT_BRANCH

default:
  tags:
    - shell

# ~~~~~~~~~~~~~~~~~~~~~~ #

stages:
  - test
  - deploy
  - unit-test

# ~~~~~~~~~~~~~~~~~~~~~~ #

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/deploy/deploy.yml
    rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

# ~~~~~~~~~~~~~~~~~~~~~~ #

#deploy-feature-to-staging:
#  stage: deploy-feature-branch
#  environment: staging
#  script:
#    - ansible-playbook -i $ANSIBLE_INVENTORY $DEPLOY_PLAYBOOK -e repo_version=${CI_COMMIT_REF_NAME} --vault-id $ANSIBLE_VAULT_FILE
#  rules:
#    - if: $CI_COMMIT_BRANCH =~ /^(master|release)$/
#      when: never
#    - if: $CI_PIPELINE_SOURCE !~ /^(web)$/
#   - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^(master|release)$/

# ~~~~~~~~~~~~~~~~~~~~~~ #

sonarqube:
  tags:
    - docker
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
      allow_failure: true
    - if: $CI_COMMIT_BRANCH =~ /^(release)$/

#fairdata-e2e:
#  stage: test
#  trigger: fairdata/fairdata-ci
#  rules:
#    - if: $CI_COMMIT_BRANCH =~ /^(master|release)$/
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^(master|release)$/

# ~~~~~~~~~~~~~~~~~~~~~~ #

unit-test:
  stage: unit-test
  script:
    - python3.8 -m virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - coverage run -m pytest
    - coverage report -m
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|release)$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^(master|release)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/



# ~~~~~~~~~~~~~~~~~~~~~~ #
