workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
    - if: '$CI_COMMIT_BRANCH == "stable"'
    - if: '$CI_COMMIT_BRANCH == "demo"'

stages:
  - test
  - deploy

run_unit_tests:
  stage: test
  script:
    - python3.8 -m virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - coverage run -m pytest
    - coverage report -m

deploy:
  stage: deploy
  environment:
    name: $CI_COMMIT_BRANCH
  script:
    - ansible-playbook --key-file $DEPLOY_KEY_FILE -i $ANSIBLE_INVENTORY $DEPLOY_PLAYBOOK
