variables:
  INSTANCE: download-$CI_COMMIT_REF_SLUG
  VERSION: $CI_COMMIT_BRANCH

include:
  - project: fairdata/fairdata-ci
    ref: staging
    file:
      - /templates/deploy.yml
      - /templates/review.yml

stages:
  - test
  - deploy
  - clean

run_unit_tests:
  stage: test
  tags:
    - shell
  script:
    - python3.8 -m virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - coverage run -m pytest
    - coverage report -m
