workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
    - if: '$CI_COMMIT_BRANCH == "stable"'
    - if: '$CI_COMMIT_BRANCH == "demo"'
    - if: '$CI_COMMIT_BRANCH == "staging"'

include:
  - project: fairdata/fairdata-ci
    ref: staging
    file:
      - /templates/deploy.yml

stages:
  - test
  - deploy

run_unit_tests:
  stage: test
  script:
    - python3.8 -m virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - coverage run -m pytest
    - coverage report -m
