---
variables:
  GITLAB_ENV: test
  SERVICE: ${SERVICE}

default:
  tags:
    - shell

stages:
  - test
  - deploy
  - e2e-test

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/deploy/deploy-jobs.yaml
      - /templates/test/test-jobs.yaml

# ------------------------

deploy:
  extends: .deploy-job
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

deploy-feature:
  extends: .deploy-feature-job
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

sonarqube:
  stage: test
  extends: .sonarqube-job
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

unit-test:
  stage: test
  tags:
    - docker
  image:
    name: python:3.8
  interruptible: true
  script:
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - coverage run -m pytest
    - coverage report -m
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

fairdata-e2e:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

fairdata-e2e-feature:
  stage: e2e-test
  trigger: fairdata/fairdata-ci
  variables:
    GITLAB_ENV: staging
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
