version: '3.8'

services:
  download-server:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-download-server
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - type: volume
        source: download-ida-storage
        target: /mnt/download-ida-storage
      - type: volume
        source: download-service-cache
        target: /mnt/download-service-cache
    environment:
      DOWNLOAD_SETTINGS: '/usr/local/fd/fairdata-download/settings.cfg'
      DOWNLOAD_TEST_DATA: '/usr/local/fd/fairdata-download/e2e-test-settings.cfg'
    configs:
      - source: download-settings
        target: '/usr/local/fd/fairdata-download/settings.cfg'
      - source: download-e2e-settings
        target: '/usr/local/fd/fairdata-download/e2e-test-settings.cfg'

  download-generator:
    image: fairdata-docker.artifactory.ci.csc.fi/fairdata-download-generator
    volumes:
      - .:/app
      - type: volume
        source: download-ida-storage
        target: /mnt/download-ida-storage
      - type: volume
        source: download-service-cache
        target: /mnt/download-service-cache
    environment:
      DOWNLOAD_SETTINGS: '/usr/local/fd/fairdata-download/settings.cfg'
    configs:
      - source: download-settings
        target: '/usr/local/fd/fairdata-download/settings.cfg'

  download-rabbitmq:
    image: fairdata-docker.artifactory.ci.csc.fi/rabbitmq:management
    hostname: download-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: download
      RABBITMQ_DEFAULT_PASS: download
      RABBITMQ_DEFAULT_VHOST: download
    ports:
      - 15672:15672

  fairdata-nginx:
    image: fairdata-docker.artifactory.ci.csc.fi/nginx
    configs:
      - source: fairdata-nginx-config
        target: '/etc/nginx/nginx.conf'
      - source: fairdata-ssl-certificate
        target: '/etc/pki/tls/certs/ssl.crt.pem'
      - source: fairdata-ssl-certificate-key
        target: '/etc/pki/tls/private/ssl.key.pem'
      - source: download-nginx-config
        target: '/etc/nginx/sites-enabled/download'
    ports:
      - 443:443

configs:
  download-settings:
    external: True
  download-e2e-settings:
    external: True
  download-nginx-config:
    external: True

  fairdata-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True

volumes:
  download-ida-storage:
    external: True
  download-service-cache:
    external: True
