[tool.poetry]
name = "fairdata-download-service"
version = "1.2.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
celery = "<5.0"
Flask = "^1.1.2"
gunicorn = "^20.1.0"
marshmallow = "^3.11.1"
pika = "^1.2.0"
PyJWT = "<2.0.0"
python-dotenv = "^0.17.1"
requests = "^2.25.1"
SQLAlchemy = "^1.4.13"

[tool.poetry.dev-dependencies]
flask-swagger = "^0.2.14"
flask-swagger-ui = "^3.36.0"
pylint = "^2.8.2"
pytest = "^6.2.4"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
