#!/usr/bin/env bash
#--------------------------------------------------------------------------------
# This script is used to configure and manage a local development instance of
# the download service. It should NOT be used in production.
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`

source $UTILS/init-dev-script.sh

#--------------------------------------------------------------------------------

if [ "$ENVIRONMENT" = "DEV" ]; then
    PERMS="go+rwX"
else
    PERMS="g+rwX,o-rwx"
fi

chown -R root:download $ROOT
chmod -R $PERMS $ROOT

