#!/usr/bin/env bash
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
SCRIPT_NAME=`basename $SCRIPT`
UTILS=`dirname "$SCRIPT"`

source $UTILS/init-dev-script.sh

if [ -z "$1" ]; then
    echo "Usage: $SCRIPT_NAME cli_command" >&2
    exit 1
fi

#--------------------------------------------------------------------------------

FLASK_APP="download"
export FLASK_APP

cd $ROOT
source $ROOT/venv/bin/activate

flask generator $*
