#!/usr/bin/env bash
#--------------------------------------------------------------------------------
# This script is used to execute autonated tests in a local development
# instance of the download service. It should NOT be used in production.
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`

source $UTILS/init-dev-script.sh

#--------------------------------------------------------------------------------

cd $ROOT
source venv/bin/activate

coverage run -m pytest -W ignore::urllib3.exceptions.InsecureRequestWarning

