#!/usr/bin/env bash
#--------------------------------------------------------------------------------
# This script is used to execute autonated tests in a local development
# instance of the download service. It should NOT be used in production.
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
UTILS=`dirname "$SCRIPT"`

source $UTILS/init-dev-script.sh

#--------------------------------------------------------------------------------

$UTILS/run-unit-tests

if [ $? -eq 0 ]; then
    $UTILS/run-behavioral-tests
fi
