#!/usr/bin/env bash
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
SCRIPT_NAME=`basename $SCRIPT`
CLI=`dirname "$SCRIPT"`

source $CLI/init-cli-script.sh
source $DOWNLOAD_VENV/bin/activate

cd $ROOT

flask generator $*
