#!/usr/bin/env bash
#--------------------------------------------------------------------------------
# This script is used to publish download event records to metrics.fairdat.fi
# based on download event details extracted from the download database file.
# Extreme care should be taken when publishing events to production, and this
# should only be done after extensive testing against metrics.fd-test.csc.fi
#--------------------------------------------------------------------------------

SCRIPT="$(realpath $0)"
METRICS=`dirname "$SCRIPT"`
ROOT=`dirname "$METRICS"`

#--------------------------------------------------------------------------------

if [ -z "$DOWNLOAD_SETTINGS" ]; then
    DOWNLOAD_SETTINGS="$ROOT/dev_config/settings.cfg"
fi

if [ ! -f "$DOWNLOAD_SETTINGS" ]; then
    echo "Could not find service configuration file '${DOWNLOAD_SETTINGS}'! Exiting" >&2
    exit 1
fi

if [ -z "$EVENTS_SNAPSHOT_FILE" ]; then
    EVENTS_SNAPSHOT_FILE="$METRICS/events.json"
fi

if [ ! -f "$EVENTS_SNAPSHOT_FILE" ]; then
    echo "Could not find events file '${EVENTS_SNAPSHOT_FILE}'! Exiting" >&2
    exit 1
fi

source $ROOT/venv/bin/activate
source $DOWNLOAD_SETTINGS

if [ -z "$FDWE_API" ]; then
    echo "The variable 'FDWE_API' is not defined! Exiting" >&2
    exit 1
fi

ENVIRONMENT="PRODUCTION"

export ENVIRONMENT
export EVENTS_SNAPSHOT_FILE
export FDWE_API
export FDWE_TOKEN

python $METRICS/lib/publish-events.py
